#!/usr/bin/env bash
# Reads the stack from docs/03-adr.md, installs the matching preset scripts,
# and enables the stack-dependent CI jobs. Phase 3.
#
#   ./scripts/init-stack.sh            # detect from the ADR
#   ./scripts/init-stack.sh python     # or state it explicitly
#
# Idempotent: safe to re-run. Overwrites scripts/, rewrites the CI jobs.

set -euo pipefail
cd "$(dirname "$0")/.."

ADR="docs/03-adr.md"
CI=".github/workflows/ci.yml"
STACK="${1:-}"

# ---------- detect ----------
if [ -z "$STACK" ]; then
  if [ ! -f "$ADR" ]; then
    echo "error: $ADR not found, and no stack argument given." >&2
    echo "Complete Phase 2 first, or run: $0 <node|python|go|ruby|php>" >&2
    exit 1
  fi

  # Search the Decision and Stack sections only. Searching the whole ADR would
  # match stacks named in the rejected options, which is the wrong answer.
  HAY=$(awk 'tolower($0) ~ /^#+ *(decision|stack)/{f=1;next} f && /^#+ /{f=0} f' "$ADR" | tr '[:upper:]' '[:lower:]')
  [ -z "$HAY" ] && HAY=$(tr '[:upper:]' '[:lower:]' < "$ADR")

  MATCHES=""
  echo "$HAY" | grep -qE 'node|typescript|javascript|next\.?js|react|express|nest|remix|vue|svelte' && MATCHES="$MATCHES node"
  echo "$HAY" | grep -qE 'python|django|fastapi|flask|pytest'                                       && MATCHES="$MATCHES python"
  echo "$HAY" | grep -qE '\bgo\b|golang|gin |echo framework|fiber'                                   && MATCHES="$MATCHES go"
  echo "$HAY" | grep -qE 'ruby|rails|sinatra'                                                        && MATCHES="$MATCHES ruby"
  echo "$HAY" | grep -qE 'php|laravel|symfony'                                                       && MATCHES="$MATCHES php"

  # shellcheck disable=SC2086
  set -- $MATCHES
  if [ "$#" -eq 0 ]; then
    echo "Could not determine the stack from $ADR." >&2
    echo "Run: $0 <node|python|go|ruby|php>" >&2
    exit 1
  elif [ "$#" -gt 1 ]; then
    # A full-stack project may legitimately name two. Ambiguity is a human
    # decision, not something to guess at.
    echo "Ambiguous — the ADR mentions more than one stack: $*" >&2
    echo "Run: $0 <one of the above>" >&2
    exit 1
  fi
  STACK="$1"
  echo "Detected stack from ADR: $STACK"
fi

PRESET="presets/$STACK"
[ -d "$PRESET" ] || { echo "error: no preset for '$STACK'. Available: $(ls presets | tr '\n' ' ')" >&2; exit 1; }

# ---------- install scripts ----------
for f in setup test test-holdout lint audit dev; do
  cp "$PRESET/$f.sh" "scripts/$f.sh"
  chmod +x "scripts/$f.sh"
done
echo "Installed 6 scripts from $PRESET"

# ---------- enable CI jobs ----------
# Command substitution strips trailing newlines, so pass the file path and let
# python read it — the block's trailing newline is structurally significant.
RUNTIME_FILE="$PRESET/ci-runtime.yml"

python3 - "$CI" "$RUNTIME_FILE" <<'PY'
import re, sys
path, runtime_file = sys.argv[1], sys.argv[2]
runtime = open(runtime_file).read()
if not runtime.endswith("\n"):
    runtime += "\n"
s = open(path).read()

# Strip any previously generated jobs so re-running does not stack duplicates.
s = re.sub(r'\n  # >>> generated by init-stack\.sh.*?# <<< generated\n', '\n', s, flags=re.S)
# Drop the commented placeholders on first run.
s = re.sub(r'\n  # Phase 3: uncomment.*?(?=\n  # Phase 3: uncomment|\Z)', '\n', s, flags=re.S)

s = s.rstrip() + f"""

  # >>> generated by init-stack.sh — re-run to change stack
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
{runtime}      - run: ./scripts/setup.sh
      - run: ./scripts/test.sh
      - run: ./scripts/test-holdout.sh
      - run: ./scripts/lint.sh

  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
{runtime}      - run: ./scripts/setup.sh
      - run: ./scripts/audit.sh
  # <<< generated
"""
open(path,'w').write(s)
PY

python3 -c "import yaml,sys; d=yaml.safe_load(open('$CI')); print('CI jobs:', ', '.join(d['jobs']))" \
  || { echo "error: generated CI is not valid YAML" >&2; exit 1; }

# ---------- report ----------
cat <<EOF

Stack: $STACK

Next:
  1. Check scripts/ matches how this project actually runs — presets assume
     conventional layout, and yours may differ.
  2. Fill the PROJECT sections of AGENTS.md (Phase 3 prompt).
  3. Commit, push, and confirm the Actions tab is green BEFORE writing any code.
EOF
